spring:
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-id: github
            client-secret: secret
          vk:
            client-name: VK
            client-id: id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            scope:
              - email
              - phone_number
              - friends
              - photos
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: "https://api.vk.com/method/users.get?v=5.89&fields=sex,city,country,photo_max,has_photo"
            user-name-attribute: name
            user-info-authentication-method: query

